version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Build done

  post_build:
    commands:
      - echo Deploying
      - printf "%s\n" "$EC2_PEM_KEY" > poc22.pem
      - sed -i 's/\r$//' poc22.pem
      - chmod 400 poc22.pem
      - ssh -i poc22.pem -o StrictHostKeyChecking=no ec2-user@65.0.205.246 "cd poc22-nodejs-app && git pull && npm install && pkill node || true && nohup node app.js > app.log 2>&1 &"
